name: pycppad
channels:
  - conda-forge
dependencies:
  - libboost-devel
  - libboost-python-devel
  - eigenpy
  - python
  - cppad
  - cppadcodegen
  - cmake
  - pkg-config
  - ninja
  - cxx-compiler
  - clangxx
  - doxygen
